<?php
/**
 * Plesk Database Setup Script (Site User Version)
 * 
 * This script helps configure an existing database for the Shluchim Farbrengens site.
 * 
 * USAGE:
 * 1. Create a database and user in Plesk control panel (Websites & Domains > Databases)
 * 2. Visit this script in your browser: https://yourdomain.com/plesk-setup.php
 * 3. Enter your database credentials
 * 4. The script will create config.php and import the schema
 * 5. DELETE THIS FILE after setup is complete!
 */

// Security: Only allow access if config.php doesn't exist
if (file_exists(__DIR__ . '/config.php')) {
    die('
    <html>
    <head><title>Setup Already Complete</title>
    <style>body{font-family:system-ui,sans-serif;max-width:600px;margin:50px auto;padding:20px;background:#f5f5f5;}
    .box{background:white;padding:30px;border-radius:8px;box-shadow:0 2px 10px rgba(0,0,0,0.1);}
    h1{color:#6B2C3E;margin-top:0;}
    .warning{background:#fff3cd;border:1px solid #ffc107;padding:15px;border-radius:4px;}</style>
    </head>
    <body><div class="box">
    <h1>⚠️ Setup Already Complete</h1>
    <p class="warning">config.php already exists. If you need to reconfigure, delete config.php first.</p>
    <p><strong>Security:</strong> Please delete <code>plesk-setup.php</code> from your server.</p>
    </div></body></html>
    ');
}

$message = '';
$error = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_name = trim($_POST['db_name'] ?? '');
    $db_user = trim($_POST['db_user'] ?? '');
    $db_pass = $_POST['db_pass'] ?? '';
    $import_schema = isset($_POST['import_schema']);
    
    if (empty($db_name) || empty($db_user)) {
        $error = 'Database name and username are required.';
    } else {
        // Test database connection
        try {
            $dsn = "mysql:host={$db_host};dbname={$db_name};charset=utf8mb4";
            $pdo = new PDO($dsn, $db_user, $db_pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);
            
            // Connection successful - create config.php
            $configContent = '<?php
/**
 * Shluchim Zoom Farbrengens Configuration
 *
 * AUTO-GENERATED by plesk-setup.php
 * Generated: ' . date('Y-m-d H:i:s') . '
 */

// Database Configuration
define(\'DB_HOST\', \'' . addslashes($db_host) . '\');
define(\'DB_NAME\', \'' . addslashes($db_name) . '\');
define(\'DB_USER\', \'' . addslashes($db_user) . '\');
define(\'DB_PASS\', \'' . addslashes($db_pass) . '\');

// Debug mode (set to false in production)
define(\'DEBUG_MODE\', false);

/**
 * Get database connection
 */
function getDbConnection() {
    static $pdo = null;

    if ($pdo === null) {
        try {
            $dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4";
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            if (DEBUG_MODE) {
                die("Connection failed: " . $e->getMessage());
            } else {
                die("Database connection error. Please try again later.");
            }
        }
    }

    return $pdo;
}

/**
 * Start secure session
 */
function startSecureSession() {
    if (session_status() === PHP_SESSION_NONE) {
        session_start();
    }
}

/**
 * Check if user is logged in
 */
function isLoggedIn() {
    startSecureSession();
    return isset($_SESSION[\'admin_logged_in\']) && $_SESSION[\'admin_logged_in\'] === true;
}

/**
 * JSON response helper
 */
function jsonResponse($success, $data = null, $message = \'\', $code = 200) {
    http_response_code($code);
    header(\'Content-Type: application/json\');
    echo json_encode([
        \'success\' => $success,
        \'data\' => $data,
        \'message\' => $message
    ]);
    exit;
}

/**
 * Sanitize input
 */
function sanitizeInput($input) {
    if ($input === null) return null;
    return htmlspecialchars(trim($input), ENT_QUOTES, \'UTF-8\');
}
?>';

            // Write config file
            if (file_put_contents(__DIR__ . '/config.php', $configContent) === false) {
                $error = 'Failed to write config.php. Check file permissions.';
            } else {
                // Set secure permissions
                @chmod(__DIR__ . '/config.php', 0640);
                
                $message = '✓ config.php created successfully!';
                
                // Import schema if requested
                if ($import_schema && file_exists(__DIR__ . '/database.sql')) {
                    $sql = file_get_contents(__DIR__ . '/database.sql');
                    
                    // Split into individual statements (simple split, handles most cases)
                    $statements = array_filter(
                        array_map('trim', 
                            preg_split('/;[\r\n]+/', $sql)
                        )
                    );
                    
                    $imported = 0;
                    $errors = [];
                    
                    foreach ($statements as $statement) {
                        // Skip comments and empty statements
                        if (empty($statement) || strpos($statement, '--') === 0) {
                            continue;
                        }
                        
                        try {
                            $pdo->exec($statement);
                            $imported++;
                        } catch (PDOException $e) {
                            // Ignore "already exists" errors
                            if (strpos($e->getMessage(), 'already exists') === false && 
                                strpos($e->getMessage(), 'Duplicate') === false) {
                                $errors[] = $e->getMessage();
                            }
                        }
                    }
                    
                    $message .= "<br>✓ Database schema imported ({$imported} statements executed)";
                    
                    if (!empty($errors)) {
                        $message .= "<br>⚠️ Some statements had issues (may be normal): " . 
                                    htmlspecialchars(implode('; ', array_slice($errors, 0, 3)));
                    }
                }
                
                $success = true;
            }
            
        } catch (PDOException $e) {
            $error = 'Database connection failed: ' . htmlspecialchars($e->getMessage());
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shluchim Farbrengens - Database Setup</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: system-ui, -apple-system, sans-serif;
            background: linear-gradient(135deg, #6B2C3E 0%, #4a1e2b 100%);
            min-height: 100vh;
            margin: 0;
            padding: 20px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .container {
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.3);
            max-width: 500px;
            width: 100%;
        }
        h1 {
            color: #6B2C3E;
            margin: 0 0 10px 0;
            font-size: 24px;
        }
        .subtitle {
            color: #666;
            margin-bottom: 30px;
            font-size: 14px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
            color: #333;
        }
        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 12px;
            border: 2px solid #e0e0e0;
            border-radius: 6px;
            font-size: 14px;
            margin-bottom: 20px;
            transition: border-color 0.2s;
        }
        input:focus {
            outline: none;
            border-color: #6B2C3E;
        }
        .checkbox-group {
            margin-bottom: 25px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .checkbox-group input {
            width: 18px;
            height: 18px;
        }
        .checkbox-group label {
            margin: 0;
            font-weight: normal;
        }
        button {
            width: 100%;
            padding: 14px;
            background: #6B2C3E;
            color: white;
            border: none;
            border-radius: 6px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: background 0.2s;
        }
        button:hover {
            background: #8a3a52;
        }
        .error {
            background: #fee;
            border: 1px solid #fcc;
            color: #c00;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .success {
            background: #efe;
            border: 1px solid #cfc;
            color: #060;
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .success h3 {
            margin: 0 0 10px 0;
        }
        .next-steps {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 6px;
            margin-top: 20px;
        }
        .next-steps h3 {
            margin: 0 0 15px 0;
            color: #6B2C3E;
        }
        .next-steps ol {
            margin: 0;
            padding-left: 20px;
        }
        .next-steps li {
            margin-bottom: 10px;
        }
        .next-steps a {
            color: #6B2C3E;
        }
        .warning {
            background: #fff3cd;
            border: 1px solid #ffc107;
            padding: 12px;
            border-radius: 6px;
            margin-top: 15px;
            font-size: 13px;
        }
        .help {
            font-size: 12px;
            color: #888;
            margin-top: -15px;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔧 Database Setup</h1>
        <p class="subtitle">Configure your Shluchim Farbrengens database connection</p>
        
        <?php if ($error): ?>
            <div class="error"><?php echo $error; ?></div>
        <?php endif; ?>
        
        <?php if ($success): ?>
            <div class="success">
                <h3>Setup Complete! 🎉</h3>
                <p><?php echo $message; ?></p>
            </div>
            
            <div class="next-steps">
                <h3>Next Steps:</h3>
                <ol>
                    <li>Visit <a href="setup.php">setup.php</a> to create your admin account</li>
                    <li>Log in at <a href="admin.php">admin.php</a></li>
                    <li><strong>Delete this file</strong> (plesk-setup.php) from your server!</li>
                </ol>
            </div>
            
            <div class="warning">
                ⚠️ <strong>Security:</strong> Delete plesk-setup.php immediately after completing setup!
            </div>
        <?php else: ?>
            <form method="POST">
                <p style="background:#e3f2fd;padding:12px;border-radius:6px;font-size:13px;margin-bottom:25px;">
                    <strong>📋 First:</strong> Create a database in Plesk under<br>
                    <em>Websites & Domains → Databases → Add Database</em>
                </p>
                
                <label for="db_host">Database Host</label>
                <input type="text" id="db_host" name="db_host" value="localhost" required>
                <p class="help">Usually "localhost" for Plesk hosting</p>
                
                <label for="db_name">Database Name</label>
                <input type="text" id="db_name" name="db_name" 
                       placeholder="username_farbrengens" required
                       value="<?php echo htmlspecialchars($_POST['db_name'] ?? ''); ?>">
                <p class="help">The full database name from Plesk (includes your username prefix)</p>
                
                <label for="db_user">Database User</label>
                <input type="text" id="db_user" name="db_user" 
                       placeholder="username_farbrengens" required
                       value="<?php echo htmlspecialchars($_POST['db_user'] ?? ''); ?>">
                <p class="help">Usually same as database name in Plesk</p>
                
                <label for="db_pass">Database Password</label>
                <input type="password" id="db_pass" name="db_pass" required>
                <p class="help">The password you set when creating the database user in Plesk</p>
                
                <div class="checkbox-group">
                    <input type="checkbox" id="import_schema" name="import_schema" checked>
                    <label for="import_schema">Import database schema (database.sql)</label>
                </div>
                
                <button type="submit">Test Connection & Create Config</button>
            </form>
        <?php endif; ?>
    </div>
</body>
</html>
